version: "3.8"

services:
  ams-loki:
    container_name: ams-loki
    image: grafana/loki:latest
    restart: always
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./configurations/configs.yml:/etc/loki/config.yml
      - ./ams-loki-data/loki:/loki
    networks:
      - app-network

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    restart: always
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - /var/log:/var/log
      - /etc/hostname:/etc/hostname
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    external: true
