server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://ams-loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: docker-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          container_name: front-imc
          __path__: /var/lib/docker/containers/c3b468147f9bf902b38333e17f54aca2b025329529ee1337d2db11b0061d96c5/*-json.log

      - targets:
          - localhost
        labels:
          job: docker
          container_name: imc-backend
          __path__: /var/lib/docker/containers/16f17377f9adb3c92b4bab3ef9a0894b5caf24e89d88d9abe32ed1e22073e0d8/*-json.log

      - targets:
          - localhost
        labels:
          job: docker
          container_name: mongo
          __path__: /var/lib/docker/containers/875e017524034f9b6fdd6cd1339d4b22aa97a850b661b187837c9044e05425a5/*-json.log
