server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://ams-loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s

    relabel_configs:
      # Extraire le chemin du fichier de log Docker
      - source_labels: [__meta_docker_container_log_path]
        target_label: __path__

      # Nom du conteneur
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container_name

      # Nom de l'image Docker
      - source_labels: [__meta_docker_image_name]
        target_label: image

      # Nom du job
      - target_label: job
        replacement: docker

   # 2. NGINX log scraping   #
  ###########################
  # - job_name: nginx
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: nginx
  #         __path__: /var/log/nginx/*.log
  #         instance: nginx-local
