services:
  ams-prometheus:
    container_name: ams-prometheus
    image: prom/prometheus:v3.5.0
    restart: always
    ports:
      - 9090:9090
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles


    volumes:
      - ./configurations:/etc/prometheus
      - ./data:/prometheus
     
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    external: true
